# Commands to start on workspace startup
tasks:
  - init: curl -s -L https://github.com/wundergraph/wundergraph/releases/download/v0.90.23/wunderctl_0.90.23_Linux_x86_64.tar.gz | tar xzvf - && chmod +x wunderctl && sudo mv wunderctl /usr/local/bin/
    name: 'Download Wunderctl'
  - before: cd examples/simple
    init: npm install
    command: |
      export WG_ALLOWED_ORIGIN="https://9991-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST"
      echo "$WG_ALLOWED_ORIGIN"
      npx --yes concurrently "npm start" "npx --yes wait-on $(gp url 9991) && gp preview $(gp url 9991)/app/main/operations/Dragons"
    name: 'Start app'
# Ports to expose on workspace startup
ports:
  - port: 9991
    visibility: public
    onOpen: ignore
  - port: 9992
    visibility: private
