# Commands to start on workspace startup
tasks:
  - init: curl -s -L https://github.com/wundergraph/wundergraph/releases/download/v0.90.23/wunderctl_0.90.23_Linux_x86_64.tar.gz | tar xzvf - && chmod +x wunderctl && mv wunderctl examples/simple
    name: 'Download Wunderctl'
  - init: cd examples/simple && npm install
    command: |
      export WG_ALLOWED_ORIGIN="https://9991-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST"
      echo "$WG_ALLOWED_ORIGIN"
      npm start
    name: 'Start app'
  - init: cd examples/simple && npx --yes wait-on http://localhost:9991
    command: curl http://localhost:9991/app/main/operations/Dragons
    openMode: tab-after
    name: 'Example: Get Dragons'
# Ports to expose on workspace startup
ports:
  - port: 9991
    onOpen: open-preview
    visibility: public
