name: Engine CI
on:
  push:
    branches:
      - main
      - next
    tags-ignore:
      - '*'
    paths:
      - '**/*.go'
      - 'types/**/*'
      - 'go.mod'
      - 'go.sum'
      - '!examples/**/*'
      - '!**/*.md'
      - '.github/workflows/engine-ci.yaml'
  pull_request:
    branches:
      - main
      - next
    paths:
      - '**/*.go'
      - 'types/**/*'
      - 'go.mod'
      - 'go.sum'
      - '!examples/**/*'
      - '!**/*.md'
      - '.github/workflows/engine-ci.yaml'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  WORKING_DIRECTORY: '.'
  CI: true

jobs:
  build_test:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/go
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.12.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm install --ignore-scripts

      - run: make engine-dev

      - name: Check if git is not dirty after generating files
        run: git diff --no-ext-diff --exit-code
