name: Engine Release Preview
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs*/**'
      - '*.md'

env:
  WORKING_DIRECTORY: '.'
  CI: true

jobs:
  release-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/go
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate go types based on protobuf definitions
        run: make codegen-go

      - name: Get the previous version of the release tag
        run: echo "GORELEASER_PREVIOUS_TAG=$(git describe --abbrev=0 --tags --match "v[0-9]*" tags/${{github.ref_name}}^)" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          workdir: './cmd/wunderctl'
          distribution: goreleaser-pro
          args: changelog --config ./../../.github/goreleaser/.goreleaser-darwin.yml -o release-summary
        env:
          # custom PAT to push in https://github.com/wundergraph/homebrew-wundergraph
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_GORELEASER }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GH_AUTH_DEMO_CLIENT_ID: ${{ secrets.GH_AUTH_DEMO_CLIENT_ID }}
          GH_AUTH_DEMO_CLIENT_SECRET: ${{ secrets.GH_AUTH_DEMO_CLIENT_SECRET }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Get the previous version of the release tag
        working-directory: './cmd/wunderctl'
        run: export GITHUB_STEP_SUMMARY=$(cat release-summary)
