name: Packages Release Preview

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

env:
  CI: true

jobs:
  version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - run: pnpm boot --ignore-scripts

      - name: Remove wunderctl from lerna.json packages
        run: |
          # we don't want to publish wunderctl wrapper with lerna but it is required for lerna to work
          # otherwise lerna will not remove the workspace: protocol prefix from packages that use wunderctl
          cat <<< "$(jq -r 'del(.packages[] | select(. == "packages/wunderctl"))' lerna.json)" > lerna.json

      - name: Generate next release (dry-run)
        run: pnpm run preview:version:packages --yes

      - name: Show CHANGELOG.md
        run: echo -e "\`\`\`diff\n$(git --no-pager diff './packages/*/CHANGELOG.md')\n\`\`\`" >> $GITHUB_STEP_SUMMARY
